auth_enabled: false


server:
  http_listen_port: 3100
  grpc_listen_port: 9096


common:
  path_prefix: /data/loki
  storage:
    filesystem:
      chunks_directory: /data/loki/chunks
      rules_directory: /data/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory


schema_config:
  configs:
    - from: 2025-02-03
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h


compactor:
  working_directory: /data/loki/compactor

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_streams_per_user: 10000
  max_line_size: 256KB
  max_entries_limit_per_query: 10000


table_manager:
  retention_deletes_enabled: false
  retention_period: 0s


query_range:
  align_queries_with_step: true
  max_retries: 5
  cache_results: true


frontend:
  log_queries_longer_than: 5s
  compress_responses: true


analytics:
  reporting_enabled: false
